language: minimal

services:
  - docker

env:
  global:
    - DOCKER_ORG=radonconsortium
    - DOCKER_REPO=radon-ctt-agent
    - DOCKER_ORG_REPO="${DOCKER_ORG}/${DOCKER_REPO}"
    - REPO_DIR="radon-h2020_radon-ctt-agent"
    - REPO_URL="https://github.com/radon-h2020/radon-ctt-agent.git"
  
script:
  # Clone parent repository
  - git clone "${REPO_URL}" "${REPO_DIR}"
  #
  # Build CTT agent base container
  - docker build -t "${DOCKER_ORG_REPO}:base" "${REPO_DIR}/test-tool-modules/"
  # 
  # Build CTT agent JMeter container
  - docker build -t "${DOCKER_ORG_REPO}:jmeter" "${REPO_DIR}/test-tool-modules/jmeter/"
  #
  # Build CTT agent ApacheBench container
  - docker build -t "${DOCKER_ORG_REPO}:apachebench" "${REPO_DIR}/test-tool-modules/apachebench/"
  #
  #
  # DockerHub login
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  #
  #
  # Push CTT agent base container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:base"
  #
  # Push CTT agent JMeter container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:jmeter"
  #
  # Push CTT agent ApacheBench container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:apachebench"
  #
  #
  # DockerHub logout
  - docker logout
